# Dependencies
markdown:         redcarpet
highlighter:      rouge
plugins:          [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            ML@ITB
tagline:          'A Jekyll theme'
description:      'Student-run Machine Learning Organization at ITB'
url:              http://mlitb.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mlitb/mlitb.github.io
